spring:
  datasource:
   url: jdbc:mysql://localhost:3306/db_car?createDatabaseIfNotExist=true
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
   hibernate:
    ddl-auto: update
   properties:
      hibernate:
        format_sql:true
        show-sql=true
   platform:
       org.hibernate.dialect.MySQL5InnoDBDialect
